import Navbar from "@/components/Navbar"
import "../globals.css"

export const metadata = {
	title: "Victor Portfolio",
	description: "Generated by Victor Manuel Zerefos",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className='w-full h-auto bg-bodyColor text-lightText py-2'>
				<div className='max-w-screen-2xl mx-auto px-16 font-titleFont'>
					<Navbar />
				</div>
				{children}
			</body>
		</html>
	)
}
